import Footer from "@/components/Footer";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import SectionContainer from "@/components/SectionContainer";
import { ThemeProviders } from './theme-providers'
import { Space_Grotesk, Croissant_One } from 'next/font/google'


const inter = Inter({ subsets: ["latin"] });

const space_grotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-grotesk',
})

//fonts testing
const croissant_one = Croissant_One({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-croissant-one',
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="font-a_garamond_pro scroll-smooth">
      <body className="bg-white text-black antialiased dark:bg-gray-950 dark:text-white">
        <ThemeProviders>
        <SectionContainer>
          <div className="flex h-screen flex-col justify-between font-sans">
            <Header />
            <main className="mb-auto">{children}</main>
            <Footer />
          </div>
        </SectionContainer>
        </ThemeProviders>
      </body>
    </html>
  );
}
